# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFMp1j9ehJ1dDMZuw2g-FChSA_O2rZ7S
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import time  # 🟢 AGREGADO: Para medir el tiempo de ejecución

# ============================================
# 1. CARGA Y PREPARACIÓN DE DATOS
# ============================================

def cargar_datos():
    """Carga los datos de vinos desde tu archivo CSV"""
    df = pd.read_csv('WineQT.csv')

    # 🟢 CORRECCIÓN: Seleccionar estrictamente las variables del SQL y eliminar nulos
    cols = ['quality', 'alcohol', 'volatile acidity', 'sulphates']
    df = df[cols].dropna()

    # Variables explicativas (3 variables) y variable respuesta
    X = df[['alcohol', 'volatile acidity', 'sulphates']].values
    y = df['quality'].values.reshape(-1, 1)

    print(f"📊 Datos cargados: {X.shape[0]} observaciones, {X.shape[1]} variables explicativas")

    # Partición 80% entrenamiento, 20% prueba
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # Estandarizar Z-score (SOLO con datos de entrenamiento)
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Agregar intercepto (columna de unos) -> Ahora X tendrá 4 columnas
    X_train_with_intercept = np.hstack([np.ones((X_train_scaled.shape[0], 1)), X_train_scaled])
    X_test_with_intercept = np.hstack([np.ones((X_test_scaled.shape[0], 1)), X_test_scaled])

    print(f"✅ X_train (con intercepto): {X_train_with_intercept.shape}")
    print(f"✅ X_test (con intercepto): {X_test_with_intercept.shape}")

    return X_train_with_intercept, X_test_with_intercept, y_train, y_test

# ============================================
# 2. FUNCIONES PARA MODELO LINEAL MÚLTIPLE
# ============================================

def funcion_objetivo_lineal(theta, X, y):
    """J(θ) = (1/2m) * ||Xθ - y||²"""
    m = X.shape[0]
    residuos = X @ theta.reshape(-1, 1) - y
    return (1 / (2 * m)) * np.sum(residuos ** 2)

def gradiente_lineal(theta, X, y):
    """∇J(θ) = (1/m) * Xᵀ(Xθ - y)"""
    m = X.shape[0]
    residuos = X @ theta.reshape(-1, 1) - y
    return (1 / m) * X.T @ residuos

def hessiana_lineal(theta, X, y):
    """∇²J(θ) = (1/m) * XᵀX (constante)"""
    m = X.shape[0]
    return (1 / m) * X.T @ X

# ============================================
# 3. FUNCIONES PARA MODELO NO LINEAL MÚLTIPLE
# ============================================

def modelo_no_lineal(X, theta):
    """
    🟢 CORRECCIÓN: Modelo no lineal propuesto acorde al documento LaTeX:
    ŷ = θ₀ + exp(θ₁ * X₁ + θ₂ * X₂ + θ₃ * X₃)

    Donde X₁, X₂, X₃ son las tres variables escaladas (alcohol, acidez, sulfatos)
    X[:, 0] es la columna de unos (intercepto).
    """
    z = theta[1] * X[:, 1] + theta[2] * X[:, 2] + theta[3] * X[:, 3]
    y_pred = theta[0] + np.exp(z)

    return y_pred.reshape(-1, 1)

def funcion_objetivo_no_lineal(theta, X, y):
    """J(θ) = (1/2m) * Σ(g(x_i;θ) - y_i)²"""
    m = X.shape[0]
    residuos = modelo_no_lineal(X, theta) - y
    return (1 / (2 * m)) * np.sum(residuos ** 2)

def gradiente_no_lineal(theta, X, y):
    """Gradiente numérico usando diferencias finitas"""
    n = len(theta)
    grad = np.zeros(n)
    eps = 1e-8
    J0 = funcion_objetivo_no_lineal(theta, X, y)

    for i in range(n):
        theta_plus = theta.copy()
        theta_plus[i] += eps
        J1 = funcion_objetivo_no_lineal(theta_plus, X, y)
        grad[i] = (J1 - J0) / eps

    return grad.reshape(-1, 1)

def hessiana_no_lineal(theta, X, y):
    """Hessiana numérica usando diferencias finitas"""
    n = len(theta)
    H = np.zeros((n, n))
    eps = 1e-7
    grad0 = gradiente_no_lineal(theta, X, y)

    for i in range(n):
        theta_plus = theta.copy()
        theta_plus[i] += eps
        grad1 = gradiente_no_lineal(theta_plus, X, y)
        H[:, i] = ((grad1 - grad0).flatten()) / eps

    return H

# ============================================
# 4. MÉTODO DE NEWTON
# ============================================

def metodo_newton(func_obj, grad, hess, X, y, theta0,
                  tol=1e-6, max_iter=100, verbose=True):
    theta = theta0.copy()
    historial_J = []
    historial_theta = []

    print("\n" + "="*50)
    print("MÉTODO DE NEWTON")
    print("="*50)

    start_time = time.time()  # 🟢 Iniciar cronómetro

    for k in range(max_iter):
        g = grad(theta, X, y).flatten()
        H = hess(theta, X, y)

        # Resolver sistema lineal: H * s = -g (evita inversa explícita)
        try:
            s = np.linalg.solve(H, -g)
        except np.linalg.LinAlgError:
            print(f"⚠️ Hessiana singular en iteración {k}. Usando pseudo-inversa.")
            s = -np.linalg.pinv(H) @ g

        theta_nuevo = theta + s
        J = func_obj(theta_nuevo, X, y)
        historial_J.append(J)
        historial_theta.append(theta_nuevo.copy())

        if verbose and k % 10 == 0:
            print(f"Iter {k:3d}: J = {J:.8f}, ||g|| = {np.linalg.norm(g):.6f}")

        if np.linalg.norm(g) < tol:
            print(f"✅ Convergencia: ||g|| = {np.linalg.norm(g):.2e} < {tol}")
            break

        if np.linalg.norm(theta_nuevo - theta) < tol:
            print(f"✅ Convergencia: ||Δθ|| = {np.linalg.norm(theta_nuevo - theta):.2e} < {tol}")
            break

        theta = theta_nuevo

    tiempo_ejecucion = time.time() - start_time  # 🟢 Detener cronómetro
    condicion_H = np.linalg.cond(H)              # 🟢 Calcular Condición de Hessiana

    print(f"✅ J final = {J:.8f}")

    return {
        'theta': theta,
        'J_final': J,
        'iteraciones': len(historial_J),
        'historial_J': historial_J,
        'grad_final': grad(theta, X, y),
        'tiempo': tiempo_ejecucion,    # 🟢 Retornar métricas de la rúbrica
        'cond_H': condicion_H
    }

# ============================================
# 5. MÉTODO DE TRUST REGION
# ============================================

def metodo_trust_region(func_obj, grad, hess, X, y, theta0,
                        tol=1e-6, max_iter=100, alpha0=0.1,
                        rho_aceptar=0.25, verbose=True):
    theta = theta0.copy()
    alpha = alpha0
    historial_J = []

    print("\n" + "="*50)
    print("MÉTODO DE TRUST REGION")
    print("="*50)

    start_time = time.time()  # 🟢 Iniciar cronómetro

    for k in range(max_iter):
        g = grad(theta, X, y).flatten()
        H = hess(theta, X, y)

        # Regularizar Hessiana: H_reg = H + αI
        H_reg = H + alpha * np.eye(len(theta))

        try:
            s = np.linalg.solve(H_reg, -g)
        except np.linalg.LinAlgError:
            print(f"⚠️ Hessiana singular en iteración {k}. Usando pseudo-inversa.")
            s = -np.linalg.pinv(H_reg) @ g

        theta_propuesto = theta + s
        J_actual = func_obj(theta, X, y)
        J_propuesto = func_obj(theta_propuesto, X, y)

        reduccion_real = J_actual - J_propuesto
        if len(g.shape) == 1:
            g = g.reshape(-1, 1)
        reduccion_predicha = -g.flatten() @ s - 0.5 * s @ H @ s

        if reduccion_predicha > 0:
            rho = reduccion_real / reduccion_predicha
        else:
            rho = -1.0

        if rho > rho_aceptar:
            theta = theta_propuesto
            alpha = max(alpha * 0.7, 1e-8)
            if verbose: print(f"Iter {k:3d}: ✅ Aceptado (rho={rho:.3f}), α={alpha:.4f}")
        elif rho > 0:
            theta = theta_propuesto
            if verbose: print(f"Iter {k:3d}: ✅ Aceptado (rho={rho:.3f}), α={alpha:.4f}")
        else:
            alpha = min(alpha * 1.5, 100)
            if verbose: print(f"Iter {k:3d}: ❌ Rechazado (rho={rho:.3f}), α={alpha:.4f}")

        J = func_obj(theta, X, y)
        historial_J.append(J)

        grad_actual = grad(theta, X, y)
        if np.linalg.norm(grad_actual) < tol:
            print(f"✅ Convergencia: ||g|| = {np.linalg.norm(grad_actual):.2e} < {tol}")
            break

        if alpha > 50:
            print(f"⚠️ α muy grande ({alpha:.2f}). Deteniendo.")
            break

    tiempo_ejecucion = time.time() - start_time  # 🟢 Detener cronómetro
    condicion_H = np.linalg.cond(H_reg)          # 🟢 Calcular Condición con Hessiana regularizada

    print(f"✅ J final = {J:.8f}")

    return {
        'theta': theta,
        'J_final': J,
        'iteraciones': len(historial_J),
        'historial_J': historial_J,
        'grad_final': grad(theta, X, y),
        'tiempo': tiempo_ejecucion,    # 🟢 Retornar métricas de la rúbrica
        'cond_H': condicion_H
    }

# ============================================
# 6. MÉTRICAS DE EVALUACIÓN
# ============================================

def calcular_metricas(y_true, y_pred):
    """Calcula MSE, RMSE y R²"""
    mse = np.mean((y_true - y_pred) ** 2)
    rmse = np.sqrt(mse)

    ss_total = np.sum((y_true - np.mean(y_true)) ** 2)
    ss_residual = np.sum((y_true - y_pred) ** 2)
    r2 = 1 - (ss_residual / ss_total)

    return {'MSE': mse, 'RMSE': rmse, 'R2': r2}

# ============================================
# 7. FUNCIÓN PRINCIPAL
# ============================================

def main():
    print("="*60)
    print("OPTIMIZACIÓN NUMÉRICA - NEWTON vs TRUST REGION")
    print("Dataset: WineQT (Vinos) de Kaggle")
    print("="*60)

    print("\n📥 Cargando datos...")
    X_train, X_test, y_train, y_test = cargar_datos()

    # ============================================
    # MODELO LINEAL MÚLTIPLE
    # ============================================
    print("\n" + "="*60)
    print("MODELO LINEAL MÚLTIPLE")
    print("="*60)

    n_features = X_train.shape[1] # Será 4 (3 variables + 1 intercepto)
    theta0_lineal = np.zeros(n_features)

    print("\n🔵 EJECUTANDO NEWTON...")
    resultado_newton_lineal = metodo_newton(
        funcion_objetivo_lineal, gradiente_lineal, hessiana_lineal,
        X_train, y_train, theta0_lineal, tol=1e-8, max_iter=100
    )

    print("\n🟢 EJECUTANDO TRUST REGION...")
    resultado_tr_lineal = metodo_trust_region(
        funcion_objetivo_lineal, gradiente_lineal, hessiana_lineal,
        X_train, y_train, theta0_lineal, tol=1e-8, max_iter=100, alpha0=0.1
    )

    # ============================================
    # MODELO NO LINEAL MÚLTIPLE
    # ============================================
    print("\n" + "="*60)
    print("MODELO NO LINEAL MÚLTIPLE")
    print("="*60)

    # 🟢 CORRECCIÓN: Usamos TODAS las variables para el No Lineal, igual que en el Lineal.
    # Parámetros iniciales: [θ₀, θ₁, θ₂, θ₃] -> 4 parámetros
    theta0_no_lineal = np.array([5.0, 0.1, 0.1, 0.1])

    print(f"\n📐 Modelo Exponencial: ŷ = θ₀ + exp(θ₁·X₁ + θ₂·X₂ + θ₃·X₃)")

    print("\n🔵 EJECUTANDO NEWTON (NO LINEAL)...")
    resultado_newton_nl = metodo_newton(
        funcion_objetivo_no_lineal, gradiente_no_lineal, hessiana_no_lineal,
        X_train, y_train, theta0_no_lineal, tol=1e-6, max_iter=50
    )

    print("\n🟢 EJECUTANDO TRUST REGION (NO LINEAL)...")
    resultado_tr_nl = metodo_trust_region(
        funcion_objetivo_no_lineal, gradiente_no_lineal, hessiana_no_lineal,
        X_train, y_train, theta0_no_lineal, tol=1e-6, max_iter=50, alpha0=0.5
    )

    # ============================================
    # GRÁFICAS DE CONVERGENCIA
    # ============================================
    print("\n📊 Generando gráficas de convergencia...")

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(resultado_newton_lineal['historial_J'], 'b-o', label='Newton', linewidth=2)
    axes[0].plot(resultado_tr_lineal['historial_J'], 'g-x', label='Trust Region', linewidth=2)
    axes[0].set_xlabel('Iteraciones', fontsize=12)
    axes[0].set_ylabel('J(θ)', fontsize=12)
    axes[0].set_title('Modelo Lineal Múltiple', fontsize=14)
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(resultado_newton_nl['historial_J'], 'b-o', label='Newton', linewidth=2)
    axes[1].plot(resultado_tr_nl['historial_J'], 'g-x', label='Trust Region', linewidth=2)
    axes[1].set_xlabel('Iteraciones', fontsize=12)
    axes[1].set_ylabel('J(θ)', fontsize=12)
    axes[1].set_title('Modelo No Lineal Múltiple', fontsize=14)
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('convergencia_newton_trust_region.png', dpi=300, bbox_inches='tight')

    # ============================================
    # RESUMEN FINAL (CON NUEVAS MÉTRICAS)
    # ============================================
    print("\n" + "="*60)
    print("RESUMEN FINAL (MÉTRICAS EXIGIDAS EN LA RÚBRICA)")
    print("="*60)

    y_pred_nl_n = modelo_no_lineal(X_test, resultado_newton_nl['theta'])
    y_pred_nl_tr = modelo_no_lineal(X_test, resultado_tr_nl['theta'])

    m_lin_n = calcular_metricas(y_test, X_test @ resultado_newton_lineal['theta'])
    m_lin_tr = calcular_metricas(y_test, X_test @ resultado_tr_lineal['theta'])
    m_nl_n = calcular_metricas(y_test, y_pred_nl_n)
    m_nl_tr = calcular_metricas(y_test, y_pred_nl_tr)

    resultados_tabla = {
        "Método": ["Lineal Newton", "Lineal Trust R.", "No Lineal Newton", "No Lineal Trust R."],
        "Iteraciones": [
            resultado_newton_lineal['iteraciones'], resultado_tr_lineal['iteraciones'],
            resultado_newton_nl['iteraciones'], resultado_tr_nl['iteraciones']
        ],
        "Tiempo (s)": [
            f"{resultado_newton_lineal['tiempo']:.5f}", f"{resultado_tr_lineal['tiempo']:.5f}",
            f"{resultado_newton_nl['tiempo']:.5f}", f"{resultado_tr_nl['tiempo']:.5f}"
        ],
        "Norma ∇J": [
            f"{np.linalg.norm(resultado_newton_lineal['grad_final']):.2e}",
            f"{np.linalg.norm(resultado_tr_lineal['grad_final']):.2e}",
            f"{np.linalg.norm(resultado_newton_nl['grad_final']):.2e}",
            f"{np.linalg.norm(resultado_tr_nl['grad_final']):.2e}"
        ],
        "Condición κ(H)": [
            f"{resultado_newton_lineal['cond_H']:.2f}", f"{resultado_tr_lineal['cond_H']:.2f}",
            f"{resultado_newton_nl['cond_H']:.2f}", f"{resultado_tr_nl['cond_H']:.2f}"
        ],
        "MSE Test": [
            f"{m_lin_n['MSE']:.4f}", f"{m_lin_tr['MSE']:.4f}",
            f"{m_nl_n['MSE']:.4f}", f"{m_nl_tr['MSE']:.4f}"
        ],
        "R² Test": [
            f"{m_lin_n['R2']:.4f}", f"{m_lin_tr['R2']:.4f}",
            f"{m_nl_n['R2']:.4f}", f"{m_nl_tr['R2']:.4f}"
        ]
    }

    df_resumen = pd.DataFrame(resultados_tabla)
    print("\n" + df_resumen.to_string(index=False))
    print("\n✅ Proyecto totalmente alineado a la rúbrica.")

if __name__ == "__main__":
    main()